### PR TITLE
Backport service changes to zipline fork

### PR DESCRIPTION
**Pull request by piyush-zlai**
## Summary
Based on OSS PR - https://github.com/airbnb/chronon/pull/873

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update

## Release Notes

- **New Features**
	- Introduced the Chronon Feature Fetching Service with capabilities for HTTP and gRPC services.
	- Added a new `service` project to enhance the overall project structure.
	- Implemented a new HTTP server for handling fetcher endpoints.
	- Added configuration options for metrics reporting and logging.

- **Bug Fixes**
	- Improved error handling for fetch requests and configuration loading.

- **Documentation**
	- Updated README to provide instructions for building and running the new service.
	- Added example configuration file for service setup.

- **Tests**
	- Added comprehensive unit tests for the new fetch handler and its JSON parsing functionality.

### CODE REVIEW

**Review by tchow-zlai — COMMENTED** [review]
@piyush-zlai  is this ready for review?

**Comment by piyush-zlai** [comment]
@tchow-zlai - yeah pretty much. It's a port from the OSS pr. I need to rebase to get all the test fixes in which I can do later but that won't change any of the code in this pr.

**Review by tchow-zlai — APPROVED** [review]
LGTM - want to defer to @nikhil-zlai  probably for a more contextual review.

**Review by nikhil-zlai — CHANGES_REQUESTED** [review]
LGTM overall. Lets replace the occurrences of "Feature" into something more general and we are good to go.

**Comment by piyush-zlai** [comment]
@nikhil-zlai - good for a re-look when you get a chance

**Review by nikhil-zlai — APPROVED** [review]
minor nit but lgtm!

**Pull request merged**
