### PR TITLE
Replace `npm` with `pnpm`

### PR DESCRIPTION
**Pull request by sean-zlai**
## Summary

[`pnpm`](https://pnpm.io/) vs `npm`
- Pros
  - Integrated (interactive) version manager
    - `pnpm up-deps` / (aliased `pnpm update -r -i --latest`)
    - `npm outdated` / `npm update --save-dev --save` only adhere to `package.json` semver
      - Must manually modify versions for major versions (ex. Vite 5 => 6)
      - Can use [`npx npm-check-updates`](https://github.com/raineorshine/npm-check-updates) package to provide similar functionality
  - Efficient Disk space
  - Workspace support
    - npm added [support](https://docs.npmjs.com/cli/v8/using-npm/workspaces) but not aware of any major projects using it
  - Typically [faster installs](https://pnpm.io/benchmarks) than npm
  - Slightly better developer ergonomics (`pnpm dev` vs `npm run dev`)
  - [Used](https://pnpm.io/users) by many large projects/companies (Vite, Svelte, etc)
- Cons
  - Additional install (`npm` included with Node.js)
  - Synk [support](https://docs.snyk.io/supported-languages-package-managers-and-frameworks/javascript/javascript-for-open-source?_gl=1*1gi9low*_gcl_au*MTA2ODIxOTcxNy4xNzM0Mzg4MTY2*_ga*MTEzMzg2NzM3NS4xNzM0MDIzMDg5*_ga_X9SH3KP7B4*MTczNDU0MzI4Mi40LjAuMTczNDU0MzI4Mi4wLjAuMA..#pnpm) is currently in [preview](https://app.snyk.io/org/varant-zlai/manage/beta-features)
  - package version overrides not currently applying with Synk (configuration, preview status of integration, ...). Likely because snyk is configured to scan `package-lock.json` (npm) and not `pnpm-lock.yaml` (pnpm). ([here](https://app.snyk.io/org/varant-zlai/project/f4bdc116-d05b-4937-96b5-b1f9a02872e5))

---

image

image

## Checklist
- [ ] Added Unit Tests
- [x] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update

## Summary by CodeRabbit

- **Documentation**
	- Updated README files to reflect the use of `pnpm` as the recommended package manager, including installation instructions and best practices.

- **New Features**
	- Transitioned scripts in the project to utilize `pnpm` for various tasks including development, building, and testing.

- **Configuration**
	- Modified Playwright configuration and other build configurations to use `pnpm` for starting the web server and managing dependencies.

- **Dependency Updates**
	- Updated Spark dependency version from `3.5.0` to `3.5.1` and Jackson version from `2.15.1` to `2.15.2`.

### CODE REVIEW

**Comment by sean-zlai** [comment]
@ken-zlai verified `docker-init/build.sh --all` runs successfully (`localhost:3000`)

**Review by ken-zlai — APPROVED** [review]
@sean-zlai Nice stuff! Working well for me. I just had to add the pnpm style overrides.

**Comment by sean-zlai** [comment]
> @sean-zlai Nice stuff! Working well for me. I just had to add the pnpm style overrides.

Thanks! I lost that commit after a bad rebase

**Comment by sean-zlai** [comment]
Reverted via https://github.com/zipline-ai/chronon/pull/144 due to Snyk UI `pnpm.overrides` support at this time (couldn't find a way to make it work)

**Pull request merged**
