### PR TITLE
Replace `svelte-hero-icons` and `@zipline-ai/icons` with `unplugin-icons`

### PR DESCRIPTION
**Pull request by sean-zlai**
## Summary

Replace `svelte-hero-icons` and `@zipline-ai/icons` with `unplugin-icons` which improve:

- Simplifies using other icon sets (ex. Lucide)
- Simplifies adding custom icons (see: [vite.confg.ts](https://github.com/zipline-ai/chronon/pull/133/files#diff-97c6e2c429ec483132c584137a18a1ade2ff6c3f4f6485f4a83db604d0323d7cR11-R17)
- Is well maintained
  - [unplugin-icons](https://www.npmjs.com/package/svelte-hero-icons) last released 2 days ago
  - [svelte-hero-icons](https://www.npmjs.com/package/svelte-hero-icons) last released 5 months ago)
  - Used by many frameworks using Vite including Svelte, Vue, and React.
- Installing the `vscode-iconify` [plugin](https://github.com/antfu/vscode-iconify) makes the experience 1000% better.  Also browsing iconsets using [icones.js.org](https://icones.js.org/collection/heroicons) which have quick copy/paste for "Unplugin Icons".

Before | After
--- | ---
image | image

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update

## Summary by CodeRabbit

- **New Features**
	- Introduced new icon packages for enhanced visual elements in the application.
  
- **Improvements**
	- Updated multiple components to utilize new icon imports, streamlining icon rendering and improving maintainability.
  
- **Bug Fixes**
	- Removed outdated icon dependencies to prevent potential conflicts and ensure compatibility with new imports. 

- **Documentation**
	- Added type exports from the new icon plugin for better type accessibility across the application.

### CODE REVIEW

**Comment by ken-zlai** [comment]
Something funky is going on here. Pulling the latest from this branch, `npm install`, then `npm run check` gives me 14 errors. These errors don't exist in main.

Looking at the diff, I don't see why the errors are here (related to echarts imports, etc). Could it be some weird rebase thing?

```
kenmorton@Kens-MacBook-Pro frontend % npm run check

> frontend@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: /Users/kenmorton/Documents/Git Repos/chronon/frontend
Getting Svelte diagnostics...

/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart-options.svelte.ts:1:15
Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? 
import type { EChartOption } from 'echarts';
import merge from 'lodash/merge';


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart-options.svelte.ts:115:37
Error: Parameter 's' implicitly has an 'any' type. 
                const series = Array.isArray(customOption.series) ? customOption.series : [customOption.series];
                customOption.series = series.map((s) => merge({}, baseSeriesStyle, s));
        }


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart.ts:31:37
Error: Property 'findIndex' does not exist on type '{}'. 
        // Find the series index by name
        const seriesIndex = options.series.findIndex((s) => s.name === seriesName);
        if (seriesIndex === -1) return '#000000';


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart.ts:31:48
Error: Parameter 's' implicitly has an 'any' type. 
        // Find the series index by name
        const seriesIndex = options.series.findIndex((s) => s.name === seriesName);
        if (seriesIndex === -1) return '#000000';


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:4:32
Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
        import * as echarts from 'echarts';
        import type { ECElementEvent, EChartOption } from 'echarts';
        import merge from 'lodash/merge';


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:113:8
Error: Parameter 'point' implicitly has an 'any' type. (ts)
                                        const dataIndex = firstSeries.data.findIndex(
                                                (point) => (point as [number, number])[0] === exactX
                                        );


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:300:50
Error: Parameter 'prev' implicitly has an 'any' type. (ts)

                        const nearestPoint = firstSeries.data.reduce((prev, curr) => {
                                const [prevX] = prev as [number, number];


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:300:56
Error: Parameter 'curr' implicitly has an 'any' type. (ts)

                        const nearestPoint = firstSeries.data.reduce((prev, curr) => {
                                const [prevX] = prev as [number, number];


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:313:38
Error: Parameter 'point' implicitly has an 'any' type. (ts)

                                        const exactPoint = s.data.find((point) => (point as [number, number])[0] === exactX);
                                        if (!exactPoint) return null;


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/PercentileChart/PercentileChart.svelte:3:16
Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
        import EChart from '$lib/components/EChart/EChart.svelte';
        import type { EChartOption, EChartsType } from 'echarts';
        import type { TimeSeriesItem } from '$lib/types/Model/Model';


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/joins/[slug]/+page.svelte:3:16
Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
        import EChart from '$lib/components/EChart/EChart.svelte';
        import type { EChartOption, EChartsType, ECElementEvent } from 'echarts';



/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/joins/[slug]/+page.svelte:129:56
Error: Parameter 'item' implicitly has an 'any' type. (ts)
                                if (Array.isArray(series.data)) {
                                        const matchingPointIndex = series.data.findIndex((item) => {
                                                const [itemTimestamp, itemValue] = item as [string, number];


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/joins/[slug]/+page.svelte:470:53
Error: Parameter 'point' implicitly has an 'any' type. (ts)
                                                // Find the point at the same timestamp
                                                const updatedPoint = updatedSeries.data.find((point) => {
                                                        const [pointTimestamp] = point as [number, number];


/Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/observability/+page.svelte:6:32
Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
        import { generateXAxis, generateYAxis, generateHeatmapData } from '$lib/util/heatmap-data-gen';
        import type { ECElementEvent, EChartOption, EChartsType } from 'echarts';
        import { onMount } from 'svelte';


====================================
svelte-check found 14 errors and 0 warnings in 6 files
```

**Comment by sean-zlai** [comment]
> Something funky is going on here. Pulling the latest from this branch, `npm install`, then `npm run check` gives me 14 errors. These errors don't exist in main.
> 
> Looking at the diff, I don't see why the errors are here (related to echarts imports, etc). Could it be some weird rebase thing?
> 
> ```
> kenmorton@Kens-MacBook-Pro frontend % npm run check
> 
> > frontend@0.0.1 check
> > svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
> 
> 
> ====================================
> Loading svelte-check in workspace: /Users/kenmorton/Documents/Git Repos/chronon/frontend
> Getting Svelte diagnostics...
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart-options.svelte.ts:1:15
> Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? 
> import type { EChartOption } from 'echarts';
> import merge from 'lodash/merge';
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart-options.svelte.ts:115:37
> Error: Parameter 's' implicitly has an 'any' type. 
>                 const series = Array.isArray(customOption.series) ? customOption.series : [customOption.series];
>                 customOption.series = series.map((s) => merge({}, baseSeriesStyle, s));
>         }
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart.ts:31:37
> Error: Property 'findIndex' does not exist on type '{}'. 
>         // Find the series index by name
>         const seriesIndex = options.series.findIndex((s) => s.name === seriesName);
>         if (seriesIndex === -1) return '#000000';
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/util/chart.ts:31:48
> Error: Parameter 's' implicitly has an 'any' type. 
>         // Find the series index by name
>         const seriesIndex = options.series.findIndex((s) => s.name === seriesName);
>         if (seriesIndex === -1) return '#000000';
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:4:32
> Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
>         import * as echarts from 'echarts';
>         import type { ECElementEvent, EChartOption } from 'echarts';
>         import merge from 'lodash/merge';
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:113:8
> Error: Parameter 'point' implicitly has an 'any' type. (ts)
>                                         const dataIndex = firstSeries.data.findIndex(
>                                                 (point) => (point as [number, number])[0] === exactX
>                                         );
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:300:50
> Error: Parameter 'prev' implicitly has an 'any' type. (ts)
> 
>                         const nearestPoint = firstSeries.data.reduce((prev, curr) => {
>                                 const [prevX] = prev as [number, number];
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:300:56
> Error: Parameter 'curr' implicitly has an 'any' type. (ts)
> 
>                         const nearestPoint = firstSeries.data.reduce((prev, curr) => {
>                                 const [prevX] = prev as [number, number];
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/EChart/EChart.svelte:313:38
> Error: Parameter 'point' implicitly has an 'any' type. (ts)
> 
>                                         const exactPoint = s.data.find((point) => (point as [number, number])[0] === exactX);
>                                         if (!exactPoint) return null;
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/lib/components/PercentileChart/PercentileChart.svelte:3:16
> Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
>         import EChart from '$lib/components/EChart/EChart.svelte';
>         import type { EChartOption, EChartsType } from 'echarts';
>         import type { TimeSeriesItem } from '$lib/types/Model/Model';
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/joins/[slug]/+page.svelte:3:16
> Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
>         import EChart from '$lib/components/EChart/EChart.svelte';
>         import type { EChartOption, EChartsType, ECElementEvent } from 'echarts';
> 
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/joins/[slug]/+page.svelte:129:56
> Error: Parameter 'item' implicitly has an 'any' type. (ts)
>                                 if (Array.isArray(series.data)) {
>                                         const matchingPointIndex = series.data.findIndex((item) => {
>                                                 const [itemTimestamp, itemValue] = item as [string, number];
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/joins/[slug]/+page.svelte:470:53
> Error: Parameter 'point' implicitly has an 'any' type. (ts)
>                                                 // Find the point at the same timestamp
>                                                 const updatedPoint = updatedSeries.data.find((point) => {
>                                                         const [pointTimestamp] = point as [number, number];
> 
> 
> /Users/kenmorton/Documents/Git Repos/chronon/frontend/src/routes/observability/+page.svelte:6:32
> Error: '"echarts"' has no exported member named 'EChartOption'. Did you mean 'EChartsOption'? (ts)
>         import { generateXAxis, generateYAxis, generateHeatmapData } from '$lib/util/heatmap-data-gen';
>         import type { ECElementEvent, EChartOption, EChartsType } from 'echarts';
>         import { onMount } from 'svelte';
> 
> 
> ====================================
> svelte-check found 14 errors and 0 warnings in 6 files
> ```

@ken-zlai - Fixed via https://github.com/zipline-ai/chronon/pull/133/commits/e32a91fbab03fe8be18726458732b312e0f767f5.  Was caused because setting [compilerOptions.types](https://www.typescriptlang.org/tsconfig/#types) in `tsconfig.json` sets an explicit list of types to use (ignoring others in `node_modules/@types`, etc).  We could add `echarts` to this list (which did fix the issue), but I found a better approach by re-exporting the types from `app.d.ts`.

PR is ready for a final review

image

**Review by ken-zlai — APPROVED** [review]
I like how `unplugin-icons` is more future proof in terms of switching out icon packs.

Since we are now gonna store our icons in this repo, does it make sense to delete https://github.com/zipline-ai/icons as to avoid any confusion?

**Comment by sean-zlai** [comment]
> I like how `unplugin-icons` is more future proof in terms of switching out icon packs.
> 
> Since we are now gonna store our icons in this repo, does it make sense to delete https://github.com/zipline-ai/icons as to avoid any confusion?

Possibly, or mark the repo as archived?

**Pull request merged**
